### ISSUE TITLE
ratatui prints random bytes on exit

### ISSUE THREAD

**Issue by alimkoca** [tui-rs-revival/ratatui#142]
## Description
When I execute one of the example code from your documentation, it prints random bytes on exit.

## To Reproduce
```rs
use std::{io, thread, time::Duration};
use ratatui::{
    backend::CrosstermBackend,
    widgets::{Widget, Block, Borders},
    layout::{Layout, Constraint, Direction},
    Terminal
};
use crossterm::{
    event::{self, DisableMouseCapture, EnableMouseCapture, Event, KeyCode},
    execute,
    terminal::{disable_raw_mode, enable_raw_mode, EnterAlternateScreen, LeaveAlternateScreen},
};

fn main() -> Result<(), io::Error> {
    // setup terminal
    enable_raw_mode()?;
    let mut stdout = io::stdout();
    execute!(stdout, EnterAlternateScreen, EnableMouseCapture)?;
    let backend = CrosstermBackend::new(stdout);
    let mut terminal = Terminal::new(backend)?;

    terminal.draw(|f| {
        let size = f.size();
        let block = Block::default()
            .title("Block")
            .borders(Borders::ALL);
        f.render_widget(block, size);
    })?;

    thread::sleep(Duration::from_millis(5000));

    // restore terminal
    disable_raw_mode()?;
    execute!(
        terminal.backend_mut(),
        LeaveAlternateScreen,
        DisableMouseCapture
    )?;
    terminal.show_cursor()?;

    Ok(())
}
```

## Expected behavior
To not print any byte to command line

## Screenshots
![Bildschirmfoto vom 2023-04-20 20-42-03](https://user-images.githubusercontent.com/66552942/233445884-4be02fc6-bf73-427d-a314-b3103d20b86d.png)

## Environment

- OS: Fedora 36 
- Terminal Emulator: GNOME Terminal
- Font: Monospace
- Crate version: 0.20.1
- Backend: crossterm

## Additional context
None

**Comment by sophacles** [comment]
What version of crossterm did you specify in your Cargo.toml?

**Comment by alimkoca** [comment]
crossterm version is 0.26 @sophacles

**Comment by alimkoca** [comment]
Uh, probably main problem is related to `EnableMouseCapture`.

**Comment by sophacles** [comment]
Oh I see. I can repro this when I move the mouse.

I think what's happening here is this:

Mouse events are sent from the terminal emulator to the app over the pty (stdin). Since the example app isn't reading any events (e.g. calling `event::read()` ) they are still queued up in stdin when the app exits, and the shell reads those and prints them on input. 

Similarly, without moving the mouse, and just typing letters, the same thing happens.

If i add:
```
    thread::spawn(|| loop {
        event::read();
    });
```
Just above the `thread::sleep(...)` line, the issue goes away.

Should we add that to the docs example with a comment?

@alimkoca - just FYI, check out the examples in the repo for how to handle inputs. (https://github.com/tui-rs-revival/ratatui/tree/main/examples)

**Comment by alimkoca** [comment]
I think that should be added to documentation, because everyone may not be good at Rust.

**Comment by joshka** [comment]
It's probably a good idea to turn off mouse capture if the example doesn't use mouse capture ;)

I've often seen a similar problem when a panic occurs. The way I've handled cleanup in my app is to ensure that the code that handles the terminal implements `Drop` which handles fixing the terminal up even if there's a panic e.g.:

```rust
use anyhow::{Context, Result};
use crossterm::terminal::{self, EnterAlternateScreen, LeaveAlternateScreen};
use ratatui::{backend::CrosstermBackend, Frame, Terminal};
use std::io::{self, Stdout};
use tracing::{error, info};

type Backend = CrosstermBackend<Stdout>;

pub struct UI {
    terminal: Terminal<Backend>,
}

impl UI {
    pub fn new() -> Result<Self> {
        let terminal =
            Terminal::new(Backend::new(io::stdout())).context("Failed to create terminal")?;
        Ok(Self { terminal })
    }

    pub fn start(&mut self) -> Result<()> {
        info!("Starting UI");
        terminal::enable_raw_mode()?;
        crossterm::execute!(io::stdout(), EnterAlternateScreen)?;
        self.terminal.hide_cursor()?;
        self.terminal.clear()?;
        Ok(())
    }

    pub fn draw<F>(&mut self, f: F) -> Result<()>
    where
        F: FnOnce(&mut Frame<Backend>),
    {
        self.terminal.draw(f)?;
        Ok(())
    }
}

impl Drop for UI {
    fn drop(&mut self) {
        if let Err(e) = terminal::disable_raw_mode() {
            error!("Error disabling raw mode: {}", e);
        }
        if let Err(e) = crossterm::execute!(io::stdout(), LeaveAlternateScreen) {
            error!("Error leaving alternate screen: {}", e);
        }
        if let Err(e) = self.terminal.show_cursor() {
            error!("Error showing cursor: {}", e);
        }
    }
}
```

You can also use a panic hook if you're more procedural than OO.

```rust
panic::set_hook(Box::new(|msg| {
    cleanup_tui();
    error!("Panic: {:?}", msg);
}));
```

**Comment by thecaralice** [comment]
@joshka doesn't that discard the panic message since the terminal is cleared?

**Comment by joshka** [comment]
Yes and no. I'd assumed that the drop gets called before the panic hook (but was wrong about that - it's called after).
But that's ok, as the drop wasn't clearing the terminal, just disabling raw mode and leaving the alternate screen. The same thing that the panic handler should do. So long as those things happen before the error is printed, then you're fine.
