### ISSUE TITLE
Update the style of application list

### ISSUE THREAD

**Issue by orhun** [tui-rs-revival/ratatui#179]
## Problem

See https://github.com/fdehau/tui-rs/pull/704

## Solution

We can possibly do a similar thing and split the applications into categories.

## Alternatives

None.

## Additional context

None.

**Comment by joshka** [comment]
Perhaps move this to a wiki page instead?

**Comment by thomas-mauran** [comment]
If we split it in different categories should we keep them in different markdown tables ? or maybe have something like I proposed [here](https://user-images.githubusercontent.com/78204354/238157432-59cb8fb1-a9ab-4f78-ba3e-ec631434a58e.png), I don't know which one is more readable

**Comment by joshka** [comment]
I like your categories and subjectively prefer that suggested layout over the tables that we have currently. Any prefs @orhun?
I think I'd probably also drop the author like you have (as open source projects usually have multiple authors, and the main author is visible in the repo name).

**Comment by thomas-mauran** [comment]
PR opened [here](https://github.com/tui-rs-revival/ratatui/pull/184) we can work from that

**Comment by orhun** [comment]
> I added [tui-rs-revival/ratatui/wiki/Apps](https://github.com/tui-rs-revival/ratatui/wiki/Apps) (which I copied from APPS.md)

It makes sense to separate something which is not directly related to the library but in that case we need to make use of the Wiki more often to make it visible. Maybe after #184 is merged, we can remove that file and add a note in README.md about it is now a part of the Wiki or something. I'm okay with either way and I think having a separate file definitely makes the application list more apparent to the user. Need some comments on this so maybe create a issue/discussion?

**Comment by joshka** [comment]
Closing as merged (and the wiki conversation has moved to #185
