### ISSUE TITLE
Move APPS.md in  the wiki

### ISSUE THREAD

**Issue by thomas-mauran** [tui-rs-revival/ratatui#185]
> I added [tui-rs-revival/ratatui/wiki/Apps](https://github.com/tui-rs-revival/ratatui/wiki/Apps) (which I copied from APPS.md)

It makes sense to separate something which is not directly related to the library but in that case we need to make use of the Wiki more often to make it visible. Maybe after #184 is merged, we can remove that file and add a note in README.md about it is now a part of the Wiki or something. I'm okay with either way and I think having a separate file definitely makes the application list more apparent to the user. Need some comments on this so maybe create a issue/discussion?

_Originally posted by @orhun in https://github.com/tui-rs-revival/ratatui/issues/179#issuecomment-1555948883_

**Comment by thomas-mauran** [comment]
The problem is that if we move APPS only in wiki it might be less visible by newcomers since the first thing we check is the readme. This list of apps is also very useful to get a rough idea of what we can do with ratatui. Maybe we can put the list of app in a wiki but still reference the link in the readme ?

**Comment by sayanarijit** [comment]
Agree.. wiki sounds like a better place. I think we can also make it publicly editable. These things shouldn't require approval.
