### ISSUE TITLE
`Grapheme` is not the proper term for what it is used for

### ISSUE THREAD

**Issue by Eyesonjune18** [tui-rs-revival/ratatui#200]
## Description
`Grapheme`, the term given to the subdivisions of a `Span` by the original `tui-rs` developer, is not the right word to describe what it actually contains. A _grapheme_ is essentially the smallest component of a written language that has a certain phonetic sound. For instance, `d` is a grapheme, but so is `sh`. The term stops working when considering multi-symbol graphemes.

## Expected behavior
It should probably be renamed to `Char`, or something similar, because although Unicode doesn't have chars exactly, it is at least clearer than `Grapheme`. `Symbol` may also work and is more accurate, but one of the fields is already called `Symbol` and I'm not a huge fan of fields that have the same name as their enclosing struct. I'm open to other suggestions.

**Comment by Eyesonjune18** [comment]
This isn't a bug but I can't edit the labels for some reason.

**Comment by joshka** [comment]
I wanted to agree with you on this one that Character makes much more sense, but found a link to https://www.unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries via https://github.com/joshka/ratatui/blob/849359bca61b0ac6bb98402b3792c1a250850095/src/buffer.rs#L285-L286 which explains the term grapheme as used in Unicode a bit better. Perhaps GraphemeCluster is the correct term to use.

>It is important to recognize that what the user thinks of as a “character”—a basic unit of a writing system for a language—may not be just a single Unicode code point. Instead, that basic unit may be made up of multiple Unicode code points. To avoid ambiguity with the computer use of the term character, this is called a user-perceived character. For example, “G” + grave-accent is a user-perceived character: users think of it as a single character, yet is actually represented by two Unicode code points. These user-perceived characters are approximated by what is called a grapheme cluster, which can be determined programmatically.

**Comment by a-kenji** [comment]
I agree with @joshka here, especially since that specific documentation is also linked to from the [rust-cookbook](https://rust-lang-nursery.github.io/rust-cookbook/text/string_parsing.html#collect-unicode-graphemes) from the [`grapheme`](https://docs.rs/unicode-segmentation/1.10.1/unicode_segmentation/trait.UnicodeSegmentation.html#tymethod.grapheme) function.
Which is a very [core](https://crates.io/crates/unicode-segmentation) library, with already a shared understanding by the wider community.

**Comment by Eyesonjune18** [comment]
If this is the case, it's probably fine. I think `StyledGraphemeClusters` is a bit much.
