### ISSUE TITLE
Reduce boilerplate on every `style()` call

### ISSUE THREAD

**Issue by joshka** [tui-rs-revival/ratatui#241]
## Problem
There's a lot of boilerplate for common methods like `style()`:
```rust
Paragraph::new("foo").style(Style::default().fg(Color::Blue).bg(Color::Red).add_modifier(Modifier::BOLD);
```

## Solution
Make it easier to specify styles similar to Crossterm's [Stylize](https://docs.rs/crossterm/latest/crossterm/style/trait.Stylize.html)

```rust
Paragraph::new("foo").blue().on_red().bold();
```

I think this can probably be implemented across every widget that supports style by adding a `Styled` trait and implementing a `Stylize` trait that has all the right methods (in crossterm these are generated using macros rather than the repetition I've written here).

```
pub trait Styled {
    fn style(&self) -> Style;
    fn set_style(self, style: Style) -> Self;
}

pub trait Stylize {
    fn blue(self) -> Self;
    fn on_red(self) -> Self;
    fn bold(self) -> Self;
}

impl<T> Stylize for T
where
    T: Styled,
{
    fn blue(self) -> Self {
        let style = self.style().fg(Color::Blue);
        self.set_style(style)
    }

    fn on_red(self) -> Self {
        let style = self.style().bg(Color::Red);
        self.set_style(style)
    }

    fn bold(self) -> Self {
        let style = self.style().add_modifier(Modifier::BOLD);
        self.set_style(style)
    }
}

impl<'a> Styled for Paragraph<'a> {
    fn style(&self) -> Style {
        self.style
    }
    fn set_style(self, style: Style) -> Paragraph<'a> {
        Paragraph::style(self, style)
    }
}
```

## Alternatives
Perhaps:
```rust
Paragraph::new("foo").stylize().blue().on_red().bold();
```
Not sure about other options that would make sense.

## Questions
1. How should widgets that have multiple style methods (for different parts of the widget) act?

## Additional context
This is a RFC. There are probably better ways of doing this, and I want to consider them before implementing this approach. Perhaps there's some magic that we can do using `AsRef` / `Deref` for this?

**Comment by joshka** [comment]
That seems too close to what we would be moving away from. It just drops the style(style::default() and imports Color::* etc.

**Comment by kdheepak** [comment]
I really like the idea of decreasing the boilerplate:

I think what could be really cool is some kind of "Styled String" macro that expands to the appropriate styled contented.

Here's an example of a [WIP feature in the Julia language](https://github.com/JuliaLang/julia/pull/49586): 

![image](https://github.com/tui-rs-revival/ratatui/assets/1813121/1cdd0985-e16f-4c75-bfbc-d9461bbf7ad3)

Would something like this be possible for ratatui? 

Here's example code I have for creating an input text area:

```rust
    let input = Paragraph::new(self.input.value())
      .block(Block::default().borders(Borders::ALL).title(Line::from(vec![
        Span::raw("Fuzzy Find "),
        Span::styled("(Press ", Style::default().fg(Color::DarkGray)),
        Span::styled("/", Style::default().add_modifier(Modifier::BOLD).fg(Color::Gray)),
        Span::styled(" to start, ", Style::default().fg(Color::DarkGray)),
        Span::styled("ESC", Style::default().add_modifier(Modifier::BOLD).fg(Color::Gray)),
        Span::styled(" to finish)", Style::default().fg(Color::DarkGray)),
      ])));
```

that renders a text area like this:

<img width="445" alt="image" src="https://github.com/tui-rs-revival/ratatui/assets/1813121/0caa3ff0-22c8-4726-bb48-a07082da3eb6">

Maybe it would be nicer to write something like this instead?



```rust
let input = Paragraph::new(self.input.value())
  .block(Block::default().borders(Borders::ALL).title(Line::from(
    style!["Fuzzy Find {darkgray:(Press} {bold:{gray:/}} {darkgray:to start} {bold:{gray:ESC}} {darkgray:to finish)}"]
  )));
```

**Comment by sayanarijit** [comment]
> That seems too close to what we would be moving away from. It just drops the style(style::default() and imports Color::* etc.

Ah now I get the intention... So the goal is to reduce imports. Makes sense then.

**Comment by sayanarijit** [comment]
> I really like the idea of decreasing the boilerplate.
> 
> I think what could be really cool is some kind of "Styled String" macro that expands to the appropriate styled contented.
> 
> Here's an example of a [WIP feature in the Julia language](https://github.com/JuliaLang/julia/pull/49586):
> 
> ![image](https://user-images.githubusercontent.com/1813121/245652091-1cdd0985-e16f-4c75-bfbc-d9461bbf7ad3.png)
> 
> Would something like this be possible for ratatui?
> 
> Here's example code I have for creating an input text area:
> 
> ```rust
>     let input = Paragraph::new(self.input.value())
>       .block(Block::default().borders(Borders::ALL).title(Line::from(vec![
>         Span::raw("Fuzzy Find "),
>         Span::styled("(Press ", Style::default().fg(Color::DarkGray)),
>         Span::styled("/", Style::default().add_modifier(Modifier::BOLD).fg(Color::Gray)),
>         Span::styled(" to start, ", Style::default().fg(Color::DarkGray)),
>         Span::styled("ESC", Style::default().add_modifier(Modifier::BOLD).fg(Color::Gray)),
>         Span::styled(" to finish)", Style::default().fg(Color::DarkGray)),
>       ])));
> ```
> 
> that renders a text area like this:
> 
> <img alt="image" width="445" src="https://user-images.githubusercontent.com/1813121/245652631-0caa3ff0-22c8-4726-bb48-a07082da3eb6.png">
> Maybe it would be nicer to write something like this instead?
> 
> ```rust
> let input = Paragraph::new(self.input.value())
>   .block(Block::default().borders(Borders::ALL).title(Line::from(
>     style!["Fuzzy Find {darkgray:(Press} {bold:{gray:/}} {darkgray:to start} {bold:{gray:ESC}} {darkgray:to finish)}"]
>   )));
> ```

Sounds like a good idea, but we're keeping macros gated behind a feature flag as an optional feature. So we first need to solve it without macro, then maybe add further convenience with macros.

**Comment by joshka** [comment]
P.S. this is not so much of a high priority (at least to me), so no rush on implementing this. It's not currently broken per say, just noisy.

**Comment by samyosm** [comment]
Wouldn't it lead to messy code similarly to [TailwindCSS](https://tailwindcss.com/)? And why not advocate in the documentation the use of style variables similarly to how [Charm](https://charm.sh/) has done it?

**Comment by joshka** [comment]
Some people like tailwind ;)

>And why not advocate in the documentation the use of style variables 

We can do that pretty easily. In fact I've been thinking about what it would take to make some nice styles that make UIs themeable (e.g. `Paragraph::new("foobar").style(theme.some_common_style_name)`) 

One thing to add here is that we could have this on anything that can be styled - string, span, line, text, widgets / widget parts.

>Ah now I get the intention... So the goal is to reduce imports. Makes sense then.

Sort of. It's mostly about reducing the visual noise in each line of code, to make what the code is doing shine brighter than the to the code necessary to enable it. Compare the example from above:

```rust
let input = Paragraph::new(self.input.value())
    .block(Block::default()
        .borders(Borders::ALL)
        .title(Line::from(vec![
            Span::raw("Fuzzy Find "),
            Span::styled("(Press ", Style::default().fg(Color::DarkGray)),
            Span::styled("/", Style::default().add_modifier(Modifier::BOLD).fg(Color::Gray)),
            Span::styled(" to start, ", Style::default().fg(Color::DarkGray)),
            Span::styled("ESC", Style::default().add_modifier(Modifier::BOLD).fg(Color::Gray)),
            Span::styled(" to finish)", Style::default().fg(Color::DarkGray)),
        ])
    )
);
```

With:
```rust
let input = Paragraph::new(self.input.value())
    .block(Block::default()
        .borders(Borders::ALL)
        .title(Line::from(vec![
            "Fuzzy Find ".raw(),
            "(Press ".styled().darkGrey(),
            "/".styled().bold().gray(),
            " to start, ".styled().darkGrey(),
            "ESC".styled().bold().gray(),
            " to finish)".styled().darkGrey(),
        ])
    )
);
```
Or possibly even:
```rust
let input = Paragraph::new(self.input.value())
    .block(Block::default()
        .borders(Borders::ALL)
        .title(Line::from(vec![
            "Fuzzy Find ".raw(),
            "(Press ".darkGrey(),
            "/".bold().gray(),
            " to start, ".darkGrey(),
            "ESC".bold().gray(),
            " to finish)".darkGrey(),
        ])
    )
);
```

>Maybe it would be nicer to write something like this instead?
`style!["Fuzzy Find {darkgray:(Press} {bold:{gray:/}} {darkgray:to start} {bold:{gray:ESC}} {darkgray:to finish)}"]`

Yes definitely down the track that could be a good approach too. It's definitely better in terms of removing the noise, but comes with a cost of having to define complex macro for parsing / precedence / nesting etc, which is harder code to write and maintain. The above proposal is just a new trait and some implementations I think.
