### ISSUE TITLE
add overflow panic at ratatui-0.21.0/src/layout.rs:464:22

### ISSUE THREAD

**Issue by XizheYin-NJU** [tui-rs-revival/ratatui#245]
## Description

Again, function `intersection` panics but it panics at /ratatui-0.21.0/src/layout.rs:464:22

## To Reproduce

```rust
fn main() {
    let _local4 = ratatui::layout::Rect::new(65280, 2, 29696, 640);
    let mut _local5 = ratatui::backend::TestBackend::new(37492, 37492);
    let _local12 = if let Ok(x) = ratatui::backend::Backend::size(&(_local5)) {
        x
    } else {
        use std::process;
        process::exit(0);
    };
    let _ = ratatui::layout::Rect::intersection(_local4, _local12);
}
```

## Error message
```
thread 'main' panicked at 'attempt to add with overflow', /home/yxz/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/ratatui-0.21.0/src/layout.rs:464:22
```

## Screenshots

![image](https://github.com/tui-rs-revival/ratatui/assets/62123683/6a8fd115-9456-4b99-b7fd-60397eeeba70)

**Comment by sayanarijit** [comment]
Please stop creating redundant issues for such edge cases. A single issue should be enough for a cleanup. If you want to contribute, please create a single issue or a single cleanup PR where we can have proper discussions. Closing this.
