### ISSUE TITLE
subtract with overflow at ratatui-0.21.0/src/layout.rs:470:21

### ISSUE THREAD

**Issue by XizheYin-NJU** [tui-rs-revival/ratatui#246]
## Description

This time, it's a subtract overflow in intersection at ratatui-0.21.0/src/layout.rs:470:21.

## To Reproduce

```rust
fn main() {
    let _local4 = ratatui::layout::Rect::new(1098, 19306, 19202, 75);
    let mut _local5 = ratatui::backend::TestBackend::new(19432, 768);
    let _local12 = if let Ok(x) = ratatui::backend::Backend::size(&(_local5)) {
        x
    } else {
        use std::process;
        process::exit(0);
    };
    let _ = ratatui::layout::Rect::intersection(_local4, _local12);
}
```

## Screenshots

![image](https://github.com/tui-rs-revival/ratatui/assets/62123683/e1cd1fcf-7093-4ed9-b929-909e197c66d3)

**Comment by sayanarijit** [comment]
Please stop creating redundant issues for such edge cases. A single issue should be enough for a cleanup. If you want to contribute, please create a single issue or a single cleanup PR where we can have proper discussions. Closing this.
