### ISSUE TITLE
add overflow panic in ratatui-0.21.0/src/layout.rs:465:22

### ISSUE THREAD

**Issue by XizheYin-NJU** [tui-rs-revival/ratatui#247]
## Description

In this testcase, the program will crash at ratatui-0.21.0/src/layout.rs:465:22

## To Reproduce

Crashed code is:
```
fn main() {
    let _local4 = ratatui::layout::Rect::new(37228, 65535, 65407, 9766);
    let mut _local5 = ratatui::backend::TestBackend::new(9801, 18726);
    let _local12 = if let Ok(x) = ratatui::backend::Backend::size(&(_local5)) {
        x
    } else {
        use std::process;
        process::exit(0);
    };
    let _ = ratatui::layout::Rect::intersection(_local4, _local12);
}

```

## Error Message
```
thread 'main' panicked at 'attempt to add with overflow', /home/yxz/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/ratatui-0.21.0/src/layout.rs:465:22
```

## Screenshots

![image](https://github.com/tui-rs-revival/ratatui/assets/62123683/228f8830-87f8-4ba7-b468-72adbfd95925)

**Comment by sayanarijit** [comment]
Please stop creating redundant issues for such edge cases. A single issue should be enough for a cleanup. If you want to contribute, please create a single issue or a single cleanup PR where we can have proper discussions. Closing this.
