### ISSUE TITLE
intersects panic because of add overflow at ratatui-0.21.0/src/layout.rs:478:16

### ISSUE THREAD

**Issue by XizheYin-NJU** [tui-rs-revival/ratatui#249]
## Description

In this testcase, intersects will panic at ratatui-0.21.0/src/layout.rs:478:16

## To Reproduce

fn main() {
    let _local1 = ratatui::layout::Rect::new(44, 11, 0, 65535);
    let mut _local2 = ratatui::backend::TestBackend::new(65535, 14385);
    let _local3 = if let Ok(x) = ratatui::backend::Backend::size(&(_local2)) {
        x
    } else {
        use std::process;
        process::exit(0);
    };
    let _ = ratatui::layout::Rect::intersects(_local1, _local3);
}

## Error Message
```
thread 'main' panicked at 'attempt to add with overflow', /home/yxz/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/ratatui-0.21.0/src/layout.rs:478:16
```

## Screenshots

![image](https://github.com/tui-rs-revival/ratatui/assets/62123683/5929201b-5dab-4db0-9372-76edb70f00b0)

**Comment by sayanarijit** [comment]
Please stop creating redundant issues for such edge cases. A single issue should be enough for a cleanup. If you want to contribute, please create a single issue or a single cleanup PR where we can have proper discussions. Closing this.
