### ISSUE TITLE
intersects panic at ratatui-0.21.0/src/layout.rs:475:18

### ISSUE THREAD

**Issue by XizheYin-NJU** [tui-rs-revival/ratatui#252]
## Description

This is also an integer addition overflow error, but the triggering condition for this error is not stringent; it only requires the condition of other.x + other.width to be met in order to trigger it.

## To Reproduce

```rust
fn main() {
    let _local3 = ratatui::layout::Rect::new(11051, 128, 11009, 0);
    let _local4 = ratatui::layout::Rect::new(11051, 11051, 65407, 0);
    let _ = ratatui::layout::Rect::intersects(_local3, _local4);
}
```

## Error Message
```
thread 'main' panicked at 'attempt to add with overflow', /home/yxz/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/ratatui-0.21.0/src/layout.rs:475:18
```

## Screenshots

![image](https://github.com/tui-rs-revival/ratatui/assets/62123683/e1516815-5e66-4615-966d-feee78ef7d78)

**Comment by sayanarijit** [comment]
Please stop creating redundant issues for such edge cases. A single issue should be enough for a cleanup. If you want to contribute, please create a single issue or a single cleanup PR where we can have proper discussions. Closing this.
