### ISSUE TITLE
Various quirks to be documented

### ISSUE THREAD

**Issue by mindoodoo** [tui-rs-revival/ratatui#56]
This issue serves the purpose of tracking and discussing various quirks of the crate that should be addressed in one PR.

**Comment by adamkali** [comment]
As stated [here](https://docs.rs/crossterm/latest/crossterm/event/struct.KeyEvent.html) Windows needs a `KeyEvent` specified. Otherwise repeat will be the default behavior.

**Comment by mindoodoo** [comment]
@adamkali Nothing much is being added here, do you want to maybe open a PR for the one quirk that you mentioned and we close this issue ?

**Comment by mindoodoo** [comment]
@adamkali I can't find what you're referencing, your link only links to documentation. Do you remember what you were refering to ? I'll close this issue in a day or two otherwise, we can reopen it if we need to.

**Comment by mindoodoo** [comment]
Closing for now, we can reopen if required
