### ISSUE TITLE
tui::widgets::ListItem support for tui::widgets::Paragraph

### ISSUE THREAD

**Issue by KarlHeitmann** [tui-rs-revival/ratatui#87]
## Problem
I am writing a project that makes use of `tui::widgets::ListItem` to display commit-nodes of a git Repository. Currently, I am making use of `tui::widgets::Text` to display this git graph:

![image](https://user-images.githubusercontent.com/3003032/224583832-967c4c9c-43c5-43df-8857-4c3f53c35949.png)
 
`tui::widgets::Text` displays a new line when `\n` is found on the string. It is working fine. Relevant code is [here](https://github.com/KarlHeitmann/git_explorer/blob/demo_list_item/src/ui/mod.rs#L142) and [here](https://github.com/KarlHeitmann/git_explorer/blob/889fd78842f2a40531ee391eb62cad685729b38b/src/ui/mod.rs#L48)

However, now I'd like to add color to the left side panel. I tried to use `tui::widgets::Spans` to build the `ListItem`. [Here](https://github.com/KarlHeitmann/git_explorer/blob/9a978485e70f4a478cbf0c266c596d7e6e65bcf7/src/ui/mod.rs#L31) is the new code  and here you have the screen shot

![image](https://user-images.githubusercontent.com/3003032/224584340-f7729885-abd1-42d2-827d-d20a8e614076.png)

As you can see, if a line feed char is inside a `Span`, `ListItem` won't write the next chars into a new line. But if a line feed char is inside a `Text`, `ListItem` will write the next chars into a new line. 

## Solution

My first thought was to make the `Span` widget react to a line feed char. But I think this is not the right solution, because a `Span` is meant to span one line, not to introduce new lines.

I saw the original `tui` code, and found out there is a [Text#styled](https://docs.rs/tui/latest/tui/text/struct.Text.html#method.styled) you can use and it -partially works for me-. Because yes, you can stylize a Text input and have line feeds inside and you will see a colored text and the line feeds in the `ListItem`. However, I want to colorize a -segment- of a string, not the entire string. And currently, there is no feature to build a `ListItem` from a `Vec<Text>`. I think it would be easier to build a trait to implement `ListItem` from a `Paragraph` rather than build it from a `Vec<Text>`

I am working on [git_explorer](https://github.com/KarlHeitmann/git_explorer) as a side project to better understand rust, and I have already done this [rg_explorer](https://github.com/KarlHeitmann/rg_explorer) side project to practice with rust. I found very interesting the rust language and want to master it. I am willing to work on this issue, but I probably need some help to understand this source code (or at least the relevant part of this source code to build this feature).

Best

**Comment by mindoodoo** [comment]
I had a little bit of a hard time understanding your issue and I wouldn't be surprised if I'm missing something, but I don't think implementing **ListItem** creation from **Paragraph** would really solve your issue.

I think the best way to handle it would be to split the string up into multiple spans and then use ```From<Vec<Spans<'a>>>``` to create your text element. You would need to style those Spans before creating the Text element as you will not be able to style those individually once you'll have built your Text element.

**Comment by KarlHeitmann** [comment]
> I had a little bit of a hard time understanding your issue and I wouldn't be surprised if I'm missing something, but I don't think implementing **ListItem** creation from **Paragraph** would really solve your issue.
> 
> I think the best way to handle it would be to split the string up into multiple spans and then use `From<Vec<Spans<'a>>>` to create your text element. You would need to style those Spans before creating the Text element as you will not be able to style those individually once you'll have built your Text element.

That's it! I didn't know `Vec<Spans>` would fix my problem. I tried the other combinations, but only when I tried with `Vec<Spans>` I could insert new lines on the `ListItem`. Sorry the confusion.

Best
