### ISSUE TITLE
Consider adding this project to blessed.rs list

### ISSUE THREAD

**Issue by heitorPB** [tui-rs-revival/ratatui#89]
Just a suggestion: add this project to the list of CLI crates in [Blessed.rs](https://blessed.rs/crates)

**Comment by orhun** [comment]
Pending for #97 

Related: https://github.com/nicoburns/blessed-rs/issues/72

**Comment by mindoodoo** [comment]
Closed as **ratatui** how now been added to blessed-rs ! 🍾
